        <!-- Javascripts -->
        <script src="<?= base_url()?>assets/plugins/jquery/jquery-3.4.1.min.js"></script>
        <script src="<?= base_url()?>assets/plugins/bootstrap/popper.min.js"></script>
        <script src="<?= base_url()?>assets/plugins/bootstrap/js/bootstrap.min.js"></script>
        <script src="<?= base_url()?>assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
        <script src="<?= base_url()?>assets/plugins/jquery-sparkline/jquery.sparkline.min.js"></script>
        <script src="<?= base_url()?>assets/plugins/apexcharts/dist/apexcharts.min.js"></script>
        <script src="<?= base_url()?>assets/plugins/blockui/jquery.blockUI.js"></script>
        <script src="<?= base_url()?>assets/plugins/flot/jquery.flot.min.js"></script>
        <script src="<?= base_url()?>assets/plugins/flot/jquery.flot.time.min.js"></script>
        <script src="<?= base_url()?>assets/plugins/flot/jquery.flot.symbol.min.js"></script>
        <script src="<?= base_url()?>assets/plugins/flot/jquery.flot.resize.min.js"></script>
        <script src="<?= base_url()?>assets/plugins/flot/jquery.flot.tooltip.min.js"></script>
        <script src="<?= base_url()?>assets/js/connect.min.js"></script>
        <script src="<?= base_url()?>assets/js/pages/dashboard.js"></script>
        <script src="<?= base_url()?>assets/plugins/DataTables/datatables.min.js"></script>
